// <auto-generated />
namespace CarRental.Migrations.MyEdits
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddCategpryDescriptionAndCarAdvantages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCategpryDescriptionAndCarAdvantages));
        
        string IMigrationMetadata.Id
        {
            get { return "201804021227002_AddCategpryDescriptionAndCarAdvantages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
