// <auto-generated />
namespace CarRental.Migrations.MyEdits
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class RentedCars_Adding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RentedCars_Adding));
        
        string IMigrationMetadata.Id
        {
            get { return "201803281443114_RentedCars_Adding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
